site_name: notes
site_url: https://svl.si
repo_url: https://github.com/4lxs/4lxs.github.io

nav:
  - index.md
  - blog:
    - blog/index.md
  - pl:
    - pl/README.md
    - type theory:
      - pl/type-theory/README.md
    - design:
      - pl/design/README.md
      - pl/design/pattern-matching.md
    - oil:
      - pl/oil/README.md
    - todo: pl/todo.md
  - math:
    - math/README.md
  - programming:
    - programming/design-and-software-engineering.md
    - programming/concepts-and-techniques.md
    - programming/functional-programming.md
    - programming/todo.md
    - dsa:
      - programming/dsa/README.md
      - programming/dsa/segment-tree.md
      - programming/dsa/range-query.md
      - programming/dsa/todo.md
    - programming/haskell.md
    - programming/ml.md
  - old:
    - kernel:
      - kernel/README.md
      - kernel/virtualization.md
      - debugging:
        - kernel/debugging/qemu-vm-windows-kernel-debugging.md
        - kernel/debugging/README.md
    - games:
      - games/README.md
    - ctf:
      - ctf/README.md
    - red-team:
      - kernel:
        - red-team/kernel/vbs.md
      - red-team/web.md
      - red-team/fuzzing.md
      - red-team/malware.md
      - red-team/defense-evasion.md
    - pwn:
      - stack:
        - pwn/stack/README.md
        - pwn/stack/rop.md
      - heap:
        - pwn/heap/README.md
        - pwn/heap/unsafe-unlink-exploit.md
    - malware:
      - malware/README.md
      - malware/kernel:
        - dkom:
          - malware/kernel/dkom/README.md
          - malware/kernel/dkom/hiding-processes.md
      - malware/linux.md
    - ml:
      - ml/README.md
      - ml/logistic-regression.md
      - ml/linear-regression.md
      - ml/gradient-descent.md
      - ml/neural-networks.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo  

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.action.view
    - content.action.edit
    - content.tooltips

plugins:
  - search
  - awesome-pages
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - footnotes

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
